### ISSUE TITLE
How was the data generated?

### ISSUE THREAD

**Issue by khaledhosny** [behdad/harfbuzz-testing-wikipedia#1]
I’d like to have similar testing data for a language not included here, and it would be nice to know how was the data generated to do the same.

**Comment by behdad** [comment]
It was a short (~200lines?) Python script that Roozbeh wrote.  I think I lost it.  I'll check again in my archives.

**Comment by hugolpz** [comment]
@behdad, it could interest Wikipedians and @Lingua-libre.
